config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
def new
  @product = Product.new
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def index 
end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coding</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
   <%= link_to 'Postiive Productions', root_url, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/products/new.html.erb
<br />
 <h1>Add a new course </h1>
 <%= simple_form_for @product, url: products_path do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <br />
    <%= f.submit "Create" %>
    <br />
  <% end %>
  <br />
</div>

app/views/static_pages/index.html.erb
<div class="positive">  
  <div class="frosty"> 
    <br />
    <dive class="row feature text-center">
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Custom Made Tumblers</h1>
    <br />
     <%= link_to 'Click Here to Order', new_product_path, class: 'btn btn-success' %>
    <br /><br />
  </div>  
</div>